<a href="https://colab.research.google.com/github/Cisco-TAC/data-analysis-course/blob/main/ch01-numpy-foundation/Project01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

### 0. 数据格式说明

Python list `file_stats`中有多个tuple，每个tuple中有两个元素，第一个为文件名，第二个为对应的文件大小（字节）。

In [7]:
file_stats = [
	('./dominant.py', 2480),
	('./log.py', 417),
	('./main.py', 1692),
	('./task.py', 274),
	('./video.py', 2269),
	('./__init__.py', 0),
	('./workers/color_analyzer.py', 1334),
	('./workers/color_collector.py', 2891),
	('./workers/extractor.py', 1409),
	('./workers/frame_display.py', 832),
	('./workers/__init__.py', 249),
]

In [8]:
py_file_names = [ele[0] for ele in file_stats]
py_file_sizes = [ele[1] for ele in file_stats]

### 1. 新建numpy数组

* 从Python数据新建NumPy数组`file_names`和`file_sizes`，分别存储文件名和文件大小。
* 每个数组的数据类型`dtype`分别是什么？

In [14]:
file_names = np.array(py_file_names)
file_sizes = np.array(py_file_sizes)
print(file_names)
print(file_sizes)

['./dominant.py' './log.py' './main.py' './task.py' './video.py'
 './__init__.py' './workers/color_analyzer.py'
 './workers/color_collector.py' './workers/extractor.py'
 './workers/frame_display.py' './workers/__init__.py']
[2480  417 1692  274 2269    0 1334 2891 1409  832  249]


### 2. 数组索引和切片

* 找到`file_names`数组第0个和最后一个记录
* 找到`file_names`数组中的前6个记录（0~6，不含6）
* 将`file_names`数组逆序输出

In [19]:
arr =np.array([
               [1,2,3],
               [4,5,6],
])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr[1,1]

5

In [21]:
arr[1]

array([4, 5, 6])

In [22]:
arr[:,1]

array([2, 5])

In [24]:
arr[:,1:3]

array([[2, 3],
       [5, 6]])

TypeError: ignored

In [23]:
file_names[0:6:-1]
print(file_names)

['./dominant.py' './log.py' './main.py' './task.py' './video.py'
 './__init__.py' './workers/color_analyzer.py'
 './workers/color_collector.py' './workers/extractor.py'
 './workers/frame_display.py' './workers/__init__.py']


### 3. 直接排序

* 占用空间最多的文件是多大？
* 占用空间最小的三个文件分别是多大？

### 4. 间接排序

* 占用空间最多的文件是哪个？
* 占用空间最小的三个文件分别是哪几个文件？
* 按占用空间由大到小给文件名排序。